config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [] do
    resources :contacts, only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  belongs_to :contactable, polymorphic: true

  validates :contactable_id, uniqueness: { scope: [:user_id, :contactable_type] }
end

app/models/conversant.rb
class Conversant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :admin, class_name: "User", foreign_key: "admin_id"

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  has_many :contacts, as: :contactable, dependent: :destroy
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :conversants, dependent: :destroy
  #validates uniqueness of: name
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts, dependent: :destroy
  has_many :conversants, dependent: :destroy
  # admin_groups is not a physical table but rather an association name used in the users
  # model to facilitates the relationship between users and groups where users act as admin
  has_many :admin_groups, class_name: "Group", foreign_key: "admin_id"

  # define associations for added users and groups separately
  has_many :added_users, through: :contacts, source: :contactable, source_type: "User"
  has_many :added_groups, through: :contacts, source: :contactable, source_type: "Group"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @users = current_user.added_users
    @groups = current_user.added_groups
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/index.html.erb
<div class="flex flex-col md:flex-row md:space-x-0 overflow-y-auto" style="overflow-y: hidden;">
    <div class="bg-gray-200 py-0 px-4 w-1/3 overflow-y-auto sm:h-[calc(100vh-65px)] h-[calc(75vh-65px)]" style="white-space: nowrap; text-overflow: ellipsis;">
        <div class="py-2">
            <div class="flex flex-col md:flex-row justify-between items-center py-2 ">
                <div class="text-left">
                    <h2 class="font-bold uppercase">Hello, <%= current_user.name%></h2>
                </div>
                <div class="text-right">
                    <%#= render partial: 'layouts/submenu/three_points' %>
                </div>
            </div>
            <%#= render "search/form_search" %>
        </div>

        <div class="h-auto md:h-[calc(100vh-250px)] overflow-y-auto">

            <div id="found_user">
            </div>

            <h2 class="pt-2">GROUPS</h2>
            <div id="groups">
                <%#= render @groups %>
            </div>

            <h2 class="pt-2">USERS</h2>
            <div id="users">
                <%= render @users %>
            </div>
        </div>
    </div>

    <div class="bg-gray-100 p-4 pb-2 md:col-span-1 md:w-2/3 overflow-y-auto sm:h-[calc(100vh-65px)] h-[calc(75vh-65px)]">
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Realtime Chat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="w-full">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/avatar/_avatar.html.erb
<div id="avatar_<%= instance.id %>">
    <% if instance.avatar.present? %>
    <div class="w-12 h-12 flex justify-center items-center overflow-hidden rounded-full" style=" <%= gradient_from_created_at(instance.created_at) %>">
        <%= image_tag instance.avatar, class:"w-full h-full object-cover" %>
    </div>
    <% else %>
    <div class="avatar_circle" style="padding:5px; width:46px; height:46px; outline:0px;font-size: 20px; <%= gradient_from_created_at(instance.created_at) %>">
        <%= first_letters(instance.name.to_s.upcase) %>
    </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<div class="px-2 py-3 w-full text-center flex justify-center items-center h-100">
  <% if current_user %>
    <div>
      <%= link_to(
        user_contacts_path(current_user),
        class: "text-gray-900 py-2 px-5 py-3 text-center mb-2 hover:text-emerald-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        ) do %>
        <i class="fa-solid fa-shield-cat fa-2xl text-violet-500 hover:text-emerald-400"
          style="width:150px; height:150px"></i><br>
        <div class="py-2 my-2">Start Chatting</div>
        <%end%><br>

          <div>
            <%= button_to "Logout" , destroy_user_session_path, method: :delete, class:"py-3" %>
              <%= link_to "Edit User" , edit_user_registration_path, class:"py-3" %>
          </div>
    </div>
    <% else %>
        <%= link_to(
          new_user_session_path,
        class: "text-gray-900 py-2 px-5 py-3 text-center mb-2 hover:text-emerald-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        ) do %>
        <i class="fa-solid fa-shield-cat fa-2xl text-violet-500 hover:text-emerald-400"
          style="width:150px; height:150px"></i><br>
        <div class="py-2 my-2">Start Chatting</div>
        <%end%><br>
          <% end %>
</div>

app/views/users/_user.html.erb
<div id="user_profile_<%= user.id%>">
    <div class="flex justify-between py-2 px-2 rounded-lg flex hover:bg-gray-100 <%= "bg-gray-100" if params[:id].to_i == user.id && request.url.include?("/users/") %>">
        <div class="text-left flex">
            <div class="relative inline-flex items-center justify-center">
                <div class="flex items-center justify-center relative">
                    <%= render partial: "layouts/avatar/avatar", locals: {instance: user } %>
                    <%#= render "users/mode", user: user %>
                </div>
            </div>

            <div class="text-left ">
                <%= link_to user.name, users_show_path(id: user.id),
                class: "px-3 pt-2 font-semibold text-grey-800 hover:underline hover:bg-gray-100" %>

                <div id="last_message_user_<%= user.id%>" class="px-3 pt-0">
                    <%#= last_message_room(current_user, user) if current_user.present? %>
                </div>
            </div>
        </div>
        <!-- If the url line doesn't include /users or /contacts or /groups -->
        <div id="user_count_<%= user.id if (params[:id].to_i != user.id && request.url.include?("/users")) || request.url.include?("/contacts") || request.url.include?("/groups") %>">
            <div class="text-white p-2 hidden">
                <div class="avatar_circle bg-green-500 " style="padding:5px; width:36px; height:36px; outline:0px;font-size: 16px;">
                    <div>
                        0
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>